### ISSUE TITLE
Getting red square constantly after running beagleboneblack_video code

### ISSUE THREAD

**Issue by GhaZalMo** [groupgets/LeptonModule#58]
Hi,

I have wired Flir lepton 3 to Beaglebone black according to the description in beagleboneblack_video section. After running the demo code, the red square appears on the screen only. I detached and reattached the Lepton from breakout board several times, but nothing changed. I have tested SPI pins on the Beaglebone black already and they work properly.
 I appreciate if someone would help with this issue.

**Comment by GhaZalMo** [comment]
I'm still having this issue. 
Even when I disconnect the flir Lepton, I'm getting the red square!
I've read somewhere that getting a red square means that the camera is connected to the Beaglebone black. Now I believe that it really means nothing.
Any help and suggestion is welcome!
Thank you in advance.

**Comment by honggangwang1979** [comment]
I have the same question! even when I remove the lepton module from the breakout, I'm getting the red square!

**Comment by honggangwang1979** [comment]
Done!
I find that the code is rigidly set only for /dev/spidev1.0, check your chip set and make sure you are using /dev/spidev1.0. I'll modify the beagleboneblack_video code to make it works for each spidev.

**Comment by GhaZalMo** [comment]
@honggangwang1979 It is great that you solved the problem. I'm still getting that red square. I used a spidev test and it shows that the spidev1 is active. Is there any other test that I should run? By the way, are you using a Lepton 3?

**Comment by honggangwang1979** [comment]
Hi, GhaZaiMo, The datasheet doesn't tell me what version of lepton it is,
the link of datasheet is here

https://cdn.sparkfun.com/datasheets/Sensors/Infrared/FLIR_Lepton_Data_Brief.pdf


I'm using a BeagleBone Blue board, which has two available spidev:
/dev/spidev1.0 and /dev/spidev1.1.
By defaut, the beagleboneblack_video code only works for /dev/spidev1.0,
the code is in ./software/beagleboneblack_video/SPI.cpp:
if (spi_device)
*spi_cs_fd = open(std::string("/dev/spidev1.0").c_str(), O_RDWR);
else
*spi_cs_fd = open(std::string("/dev/spidev1.0").c_str(), O_RDWR); so if you
don't want to modify the code, be sure that you are using /dev/spidev1.0.
Check the connection also. after that it should be able to work.

Best.
Honggang Wang
